### ISSUE TITLE
Rationale and motivation for this tool

### ISSUE THREAD

**Issue by alnesbit-ovo** [ovotech/mantle#36]
This looks like a very interesting tool.  Although I don't know Go I'm looking forward to investigating and using it.  There is no rationale or motivation for why this tool exists in `README.md`, although of course there must be a good reason for its existence.  What is this, and could we add it to the front page?

**Comment by eversC** [comment]
I think my [blog](https://tech.ovoenergy.com/mantle) probably covers the rationale and motivation (let me know what you think?)

Wondering whether we can add a link to that via README (again, let me know thoughts on that)...

**Comment by eversC** [comment]
I think this is largely covered off by the blog, and some details that're on the readme now.
